version: '3.1'
services:
  db:
    platform: linux/x86_64
    image: mysql
    #    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: match_day
    ports:
      - "3306:3306"